language: node_js
node_js:
- 10
- 12
- 13
os:
- linux
cache:
  directories:
  - node_modules
install: 
  - npm i
jobs:
  include:
  - stage: allow_failures
    node_js: 14
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      cleanup: true
      script: npx semantic-release
      on:
        branch: master