language: node_js
node_js:
  - 12
  - 10
  - 9
matrix:
  allow_failures:
    - node_js: 12
cache:
  directories:
  - node_modules
install: 
  - npm i
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/